### ISSUE TITLE
Block Hardness has changed bug

### ISSUE THREAD

**Issue by DragonGirl7567** [DakotaPride/create-framed#1]
The issue with the mod is that the block's hardness has possibly changed.
It takes a long time for the blocks to break (all blocks) and nothing drops

createframed-1.20.1-1.1.jar

(Sorry to bother you during time time of year. Just letting you know when you get around to it. Have a happy holiday)

**Comment by DakotaPride** [comment]
Hello! Thank you for reporting this issue! Does this only happen with trapdoors and doors? This is the case inside of the development environment testing, so please correct me if I'm wrong about this. This should be fixed soon, but may be delayed due to the holidays. When I get a chance, I'll let you know when this fix becomes available on both Modrinth and Curseforge.

**Comment by DakotaPride** [comment]
I should also note that, similar to the framed glass door and trapdoor in the base Create mod, you do mine those respective blocks faster. This is "replicated" to how Create functions as much as I possibly can have it. Sorry for the inconvenience, but I will still look into if there's any mishaps relating to it!

edit: another issue has been found where loot tables are missing, so may want to hold off breaking blocks for the time being. I do believe that the Wrench should work just fine, however.

**Comment by DragonGirl7567** [comment]
Haven’t tried on the modded blocks.
When I mean blocks, I mean ALL blocks, modded and not modded (try breaking wood, cobblestone, or any kind of block is like trying to break obsidian)

**Comment by DakotaPride** [comment]
That's related to an error inside of the mineable/pickaxe block tag. This should also be fixed soon!

**Comment by DakotaPride** [comment]
Should now be publicly available on both Modrinth and Curseforge! Let me know if the issues persist or if you come across any other ones!
