### ISSUE TITLE
[Bug] Create Fabric v0.5.1.f Patch 1 not supported

### ISSUE THREAD

**Issue by ajaxnotmeta** [DakotaPride/create-framed#11]
as title says Create Fabric 0.5.1-f-build.1417+mc1.20.1 isnt supported and prevents launching the game

**Comment by bangetto** [comment]
same here

**Comment by forgettableaccount123** [comment]
why is it not supported?

**Comment by DakotaPride** [comment]
Currently, it's not supported due to issues with updating the dependency inside of the project, preventing me from being able to support this version. Apologies for this inconvenience, I have been trying to find a fix for it and will continue!

**Comment by DakotaPride** [comment]
Should now be supported! Let me know if any of you come across anything else!

**Comment by Happy1speed** [comment]
It seems like create 0.5.1-f-build.1417+mc1.20.1 is still not supported
![snipperscreateframed](https://github.com/user-attachments/assets/f013a8ff-fc2e-4ea3-bbf5-b68fcb6f3212)

**Comment by DakotaPride** [comment]
Should now, once again, be fixed! Feel free to let me know if there's any other issues that you come across!
