### ISSUE TITLE
zh_cn translate documents

### ISSUE THREAD

**Issue by zhangjiuguan233** [DakotaPride/create-framed#12]
I'm not very familiar with githud, so I sent the zh_cn file separately, please forgive me if it causes trouble😥
[zh_cn.json](https://github.com/user-attachments/files/16486549/zh_cn.json)

**Comment by DakotaPride** [comment]
It's not too big of an issue, just a lot easier to merge into the main branch(es) from a pull request - will update the mod shortly!

**Comment by DakotaPride** [comment]
Should now be available! Let me know if there's anything else!
