### ISSUE TITLE
Pickaxe cannot mine stone

### ISSUE THREAD

**Issue by thomwoosley** [DakotaPride/create-framed#14]
Any pickaxe or pickaxe type tool can no longer mine any type of stone or block that should be mined by a pickaxe.

It's like the required tool has been deregistered.

This error started with Create: Framed version 1.5 on MC version 1.20.1.

Edit: This was on Forge.  I did not test Fabric.

**Comment by DakotaPride** [comment]
Apologies for taking so long to get to this!

It looks like I forgot to migrate the tag name changes for the "minecraft:mineable/pickaxe" tag. Should be fixed soon-ish (it's pretty late over here, so I understand if you might not get a chance to test it soon either).

**Comment by DakotaPride** [comment]
v1.5.1 - fixed mineable/pickaxe tag - is now available on both Curseforge and Modrinth! Let me know if you come across any other issues when you get the chance!
