### ISSUE TITLE
Partial tinted glass blocks don't block light even when it reasonably or partially reasonably should

### ISSUE THREAD

**Issue by FlashOfAsh** [DakotaPride/create-framed#17]
this applies to everything except the full blocks, sure this could be a technical limitation, or fabric issue, or even somehow a create fabric 0.5.1f issue, Either way, this applies to as said prior, everything except full blocks, talking panes, doors, trapdoors, etc

Here's pictures
![image](https://github.com/user-attachments/assets/23622806-b0ce-4c91-9516-077327f7a9c4)
![image](https://github.com/user-attachments/assets/9ad3f668-0e03-405f-8c2b-e9967667707e)

Create framed: v1.4.6

**Comment by DakotaPride** [comment]
This is a lighting engine limitation/issue. The game doesn't support partial lighting.

On Curseforge:
![image](https://github.com/user-attachments/assets/705baa42-43b7-4c4b-9fcb-d4ebef8c235b)

On Modrinth:
![image](https://github.com/user-attachments/assets/b6e85bee-f4b2-4006-a924-070fa8e540a3)

**Comment by DakotaPride** [comment]
If at some point in the future partial lighting does become supported by the lighting engine, then these blocks will _actually_ have their purpose, but for now it's just a decorative choice.

**Comment by FlashOfAsh** [comment]
i mean i was more thinking of them just, blocking light generally, there's no way the lighting engine is gonna have partial lighting be a thing after all

**Comment by DakotaPride** [comment]
This is how it was in early builds of the mod, and can even be seen on the mod's homepage on both Modrinth and Curseforge!
![image](https://github.com/user-attachments/assets/f8f955b8-1afa-4907-941b-236b3f88c46c)
While it may look alright in the picture, It looks atrocious in-game and actually playing with it, as it adds shadows that don't make sense being there. While I would personally love it to both function and look good, one cannot be accomplished if the other is true as well.
