### ISSUE TITLE
Framed doors loose proper funcionality on create trains

### ISSUE THREAD

**Issue by addebo019** [DakotaPride/create-framed#2]
the door animations no longer play, and their collisions are removed when used in a train.

**Comment by DakotaPride** [comment]
Apologies for the inconvenience, I am currently trying to fix this now! Thank you for letting me know about the issue, and I will let you know when a fix becomes available on both Modrinth and Curseforge!

**Comment by DakotaPride** [comment]
This also seems like a semi-common issue in a few addons (such as TFMG and DnD (Dreams & Desires))

**Comment by DakotaPride** [comment]
Apologies for the long wait, but a fix has been released on Modrinth and is currently waiting for approval on Curseforge!

**Comment by DakotaPride** [comment]
Now approved on Curseforge!
