### ISSUE TITLE
Create creative mode bar disappears items

### ISSUE THREAD

**Issue by DracoHero** [DakotaPride/create-framed#20]
This mod makes the TAB bar of the creative mode of the Create mod disappear the items

With mod:

![image](https://github.com/user-attachments/assets/5512b6fe-f4bb-4c4a-9b98-bc0723e387c9)

Without mod:

![image](https://github.com/user-attachments/assets/382a64fe-1248-4f59-bedc-7f3f01f4cb97)

**Comment by DakotaPride** [comment]
Did you figure out the issue? I'm only just now seeing this, but notice that you've marked this as "not planned"?

**Comment by DracoHero** [comment]
Well, in the end the conflict was from another Create addon mod, which I think conflicts with the other items
