### ISSUE TITLE
Colored/tinted glass can't be converted into it's framed variants or tiled version

### ISSUE THREAD

**Issue by FlashOfAsh** [DakotaPride/create-framed#21]
This is very annoying as a whole, basically despite what you'd expect you can't pop a form of glass into a stone cutter and get it's framed form out, INSTEAD you must get framed glass and do the thing from there. The most annoying part is this is probably a VERY easy fix

Versions: Fabric type of mod: 1.5.4  Minecraft version: 1.20.1   Fabric Version: 0.16.5

Expected way to fix: put basic form of glass into #c:glass/[type]
For example, Tiled tinted glass and framed tinted glass CAN'T exist in survival due to this bug, because regular tinted glass is not in #c:glass/tinted, and the mod doesn't even provide a more annoying route to get it

Image for proof:
![image](https://github.com/user-attachments/assets/60b11059-d706-43df-bd1c-625e0486d236)

**Comment by DakotaPride** [comment]
(apologies for taking a while, GitHub really needs to stop hiding notifications)

After looking at the recipe json files, it looks like there were duplicate recipes which caused this issue to occur. This should be fixed soon (depending on how long Curseforge takes to approve)

I'll make sure to let you know when the fix is live!

**Comment by DakotaPride** [comment]
Now available on both Curseforge and Modrinth!

**Comment by FlashOfAsh** [comment]
one step closer to some unknown point of this mod being exactly what people are looking for and more without people being turned away from the more!

**Comment by FlashOfAsh** [comment]
so uh, i quickly am trying it and actually NO this didn't fix the bug it seems, are you sure you can't put for example regular blue stained glass under #c:glass/blue or regular tinted glass under #c:glass/tinted ?

Btw, these are block tags, the stained framed glass blocks all have their own variant of one of these tags, and their recipe uses that tag for their crafting
