### ISSUE TITLE
Issue #21 not fixed from update for fabric

### ISSUE THREAD

**Issue by FlashOfAsh** [DakotaPride/create-framed#22]
Do note however, despite the ineffective fix this DID fix a different bug! see before the fix tiled glasses had a doubled up recipe for no reason, and hence was pretty confusing since the others didn't.

Either way this issue is entirely here on the behalf of issue #21 to make sure it is fixed, since the duplicated recipes were NOT what was needed to fix the problem, though I do get it, coding is weird that stuff COULD have solved it for how strange it works sometimes, but despite that it didn't. So just to make sure, it is probably fixed by editing the block tags to include the basic form of their glass (for example regular blue stained glass) in their respective #c:glass/[type] tag (for previous example it'd be #c:glass/blue)

Proof of blue stained glass not being in #c:glass/blue

![image](https://github.com/user-attachments/assets/2f5691d3-db1b-4b35-9e22-05906bf84e95)

Proof of tiled glass recipe no longer being duplicated:

![image](https://github.com/user-attachments/assets/5bba3d5a-e852-4795-b1af-9ed92d4bac44)

**Comment by DakotaPride** [comment]
Should now ACTUALLY be fixed, lmk again if not, I do apologise for the inconvenience this issue has caused! (both modrinth & curseforge on fabric)

**Comment by FlashOfAsh** [comment]
it is not a major inconvenience do not worry, and hey you fixed another slight bug in the process!

Just tested it and we have confirmation! Issue #21 is truly fixed now!
