### ISSUE TITLE
when running a server, opening the inventory causes the player to crash out of the server

### ISSUE THREAD

**Issue by ABSOLUTEMAX123** [DakotaPride/create-framed#4]
when looking into the logs, the culprit is this:
java.lang.NullPointerException: registry entry not present: createframed:red_stained_framed_glass_door

**Comment by DakotaPride** [comment]
What MC version and what Framed version are you running?

**Comment by DakotaPride** [comment]
If this issue is still occurring, feel free to let me know, but this issue will be marked as closed until the information that has been asked for is provided.
