### ISSUE TITLE
Invisible Framed Doors

### ISSUE THREAD

**Issue by CarJem** [DakotaPride/create-framed#6]
When doors are opened, they become invisible. Simple as it sounds. Using multiple create addon mods, such as dreams and desires.

**Comment by DakotaPride** [comment]
What MC version and what Framed version are you using? And is it on or not on trains?

If you could provide a video or other visual of the issue, it might also help

**Comment by DakotaPride** [comment]
Is this issue still occurring? If so, please respond to the above message.

**Comment by DakotaPride** [comment]
This issue has been marked as closed due to inactivity. If this issue is still happening, refer to the previous messages.
