### ISSUE TITLE
[Suggestion] Crafting recipes for dying framed glass

### ISSUE THREAD

**Issue by MarioSMB** [DakotaPride/create-framed#7]
It would be nice to be able to turn regular framed glass into colored framed glass by crafting it with dyes, thanks!

**Comment by TrickShow** [comment]
Following this, however mod author will probably tell you to just add recipes to kubejs to make this possible.

**Comment by MarioSMB** [comment]
That would indeed be a sad outcome, however I would encourage one to give them the benefit of the doubt.  

Me and my framed glass stockpile are looking forward to this quality of life addition when you find the time!

**Comment by DakotaPride** [comment]
This change will be coming soon, I've just been busy with some other projects and have been bug-testing a lot of features relating to those projects. It's been especially difficult to do so with finals having just finished up last week (now that summer's here, I can hopefully get a lot more done).

**Comment by DakotaPride** [comment]
> Following this, however mod author will probably tell you to just add recipes to kubejs to make this possible.

Nope, I actually advise against it as that could cause conflictions with the base mod once this QOL change does get added

**Comment by DakotaPride** [comment]
Now available on both Modrinth and Curseforge! Let me know if you come across any issues!
