### ISSUE TITLE
[Bug] No image for Vertical Stained Framed Glass Pane

### ISSUE THREAD

**Issue by luziyi** [DakotaPride/create-framed#9]
![2024-04-01_17-12-43](https://github.com/DakotaPride/create-framed/assets/42143394/45c00969-24d0-417b-9083-7e6a47f95fee)

**Comment by luziyi** [comment]
![2024-04-01_17 13 08](https://github.com/DakotaPride/create-framed/assets/42143394/9dab8bdc-da0f-4e3f-a2c5-394e3e19d933)

**Comment by luziyi** [comment]
Missing files in \assets\createframed\blockstates ,   NAME: vertical_[yellow]_stained_framed_glass_pane.json , please check.

**Comment by DakotaPride** [comment]
Thank you! Let me know if you come across anything else!
